version: "3.8"

services:
  neo4j:
    # image: neo4j:5.22 # latest stable 5.x version, adjust as needed
    image: neo4j:latest
    container_name: neo4j
    # restart: unless-stopped
    ports:
      - "7474:7474"   # Neo4j Browser (HTTP UI)
      - "7687:7687"   # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/letmein  # username: neo4j, password: letmein
      - NEO4J_server_memory_heap_initial__size=1G
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_PLUGINS=["apoc"] #, "graph-data-science"]
      - NEO4J_dbms_security_auth__minimum__password__length=4
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
      - ./neo4j/import:/import
